"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#c3b7b8)\
[  ](bg:#c3b7b8 fg:#191515)\
[](bg:#f38d70 fg:#c3b7b8)\
$directory\
[](fg:#f38d70 bg:#72696a)\
$git_branch\
$git_status\
[](fg:#72696a bg:#2c2525)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2c2525 bg:#403838)\
$time\
[ ](fg:#403838)\
\n$character"""

[directory]
style = "fg:#191515 bg:#f38d70"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#72696a"
format = '[[ $symbol $branch ](fg:#f9cc6c bg:#72696a)]($style)'

[git_status]
style = "bg:#72696a"
format = '[[($all_status$ahead_behind )](fg:#f9cc6c bg:#72696a)]($style)'

[nodejs]
symbol = ""
style = "bg:#2c2525"
format = '[[ $symbol ($version) ](fg:#85dacc bg:#2c2525)]($style)'

[rust]
symbol = ""
style = "bg:#2c2525"
format = '[[ $symbol ($version) ](fg:#85dacc bg:#2c2525)]($style)'

[golang]
symbol = ""
style = "bg:#2c2525"
format = '[[ $symbol ($version) ](fg:#85dacc bg:#2c2525)]($style)'

[php]
symbol = ""
style = "bg:#2c2525"
format = '[[ $symbol ($version) ](fg:#85dacc bg:#2c2525)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#403838"
format = '[[  $time ](fg:#c3b7b8 bg:#403838)]($style)'
